[package]
name = "oxterm"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
boolinator = "2.4.0"
pico-args = "0.4.1"
serialport = "4.0.1"
tui = "0.15.0"
